gems:
  - jekyll-redirect-from

# Site settings
title: Healthy Hacker
keywords: "development,software,programming,puzzles,exercise,memory,health,fitness"
description: "Welcome to the Healthy Hacker where we talk about programming,
  puzzles, memory, fitness, diet, and everything else that you, a healthy
  hacker, find interesting."
url: "http://www.healthyhacker.com"
paginate: 20
mp3url: "http://traffic.libsyn.com/healthyhacker"
itunesurl: "https://itunes.apple.com/us/podcast/healthy-hacker/id904717019"
phone: "502-324-7475"

# Build settings
markdown: kramdown
permalink: pretty

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "page"
