# Site settings
title: Healthy Hacker
description: "Everything you need to know to be a healthy hacker. We talk about
  fitness, puzzles, memory, vim, tmux, and anything else that blah blah."
baseurl: ""
url: "http://healthyhacker.com"
paginate: 3

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "page"
