# Site settings
title: Healthy Hacker

description: "Welcome to the Healthy Hacker where we talk about programming,
  productivity, puzzles, memory techniques, fitness, diet, and other amazing
  things that you, a healthy hacker, will find interesting."

url: "http://healthyhacker.com"
paginate: 3

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "page"
