gems:
  - jekyll-redirect-from

# Site settings
title: Healthy Hacker
keywords: "development,software,programming,exercise,health,fitness"
description: "Welcome to the Healthy Hacker where we talk about programming,
  productivity, puzzles, memory techniques, fitness, diet, and other amazing
  things that you, a healthy hacker, will find interesting."
url: "http://healthyhacker.com"
paginate: 3

# Build settings
markdown: kramdown
permalink: pretty

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "page"
